CREATE SCHEMA IF NOT EXISTS inventory DEFAULT CHARACTER SET utf8 ;
USE inventory;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_type ENUM('ROLE_USER', 'ROLE_ADMIN'),
    PRIMARY KEY (user_id, role_type),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
